AllCops:
  DefaultFormatter: progress
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'public/**/*'
    - 'script/**/*'
  
Style/IndentationConsistency:
  EnforcedStyle: rails          

Rails:
  Enabled: true
